# -*- coding: utf-8 -*-
"""LVADSUSR183_SajjaTarunTeja.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M_Fhzn6F5-LIN6QNV4MVSfXDbd9U_YfK

## Internal Assessment - 1
### Sajja Tarun Teja - 4391

### Lab 1
"""

# Question 1
def cpms():
  print("Welcome to Commercial Property Management System")
  print()
  w = float(input("Enter the width of the property in meters "))
  l = float(input("Enter the length of the property in meters "))
  a = w*l
  print("The area of the property is {}",format(a))
  ppms = 0
  if a<1000:
    ppms = 10
    print("This property is categorised as Small and ppms is {}".format(ppms))
  elif a<10000:
    ppms = 20
    print("This property is categorised as Medium and ppms is {}".format(ppms))
  else:
    ppms = 30
    print("This property is categorised as Large and ppms is {}".format(ppms))

  print("Therefore the total valuation of the property is Rs{}".format(a*ppms))
cpms()

# Question 2
def ihma():
  print("Welcome to Integrated Health Management App")
  age = float(input("Please enter your age: "))
  h = float(input("Please enter you height in meters:"))
  w = float(input("Please enter you weight in kgs: "))
  bmi = w/(h*h)
  if bmi > 25:
    print("Your BMI is {}".format(bmi))
    print("You are obese")
    if age<30:
      print("Please lift weights and reduce calories")
    else:
      print("Please start soft paced cardio")
  elif bmi >15:
    print("Your BMI is {}".format(bmi))
    print("You are healthy. Please do follow a healthy die for longetivity")
  else:
    print("Your BMI is {}".format(bmi))
    print("You are underweight buddy. Please eat more protien")
ihma()

# Question 3
sdict = {}

def add(id,sd):
  sdict[id] = sd
  print(sdict[id])

def update(id,k,v):
  sdict[id][k] = v
  print(sdict[id])

def retrieve():
  print(sdict)

def preport(id):
  print(sdict[id])

add("Tharun", {"Excel":10,"Sql":9,"Python":9})
add("Alesha", {"Excel":10,"Sql":10,"Python":10})
add("Vishal", {"Excel":8,"Sql":9,"Python":7})
add("Abhishek", {"Excel":6,"Sql":9,"Python":10})

update("Tharun","Excel",8)

retrieve()

preport("Vishal")

"""### Lab 2"""

# Question 4
movie = {
    "Children" : ["Peppa Pig", "Frozen", "Cindrella"],
    "Teen" : ["Madagascar", "Sky High", "Incredibles"],
    "Adult" : ["Family Guy", "Modern Family", "Love Again"],
    "Senior": ["GodFather", "Predestination", "Shutter Island"]
}

def cre():
  print("Welcome to the content recomender engine")
  age = int(input("Please enter you age before we begin suggesting you "))
  cat = ""
  if age<13:
    cat = "Children"
    print("You fall under Children Categroy ")
    print("Here are some suggestions for you {}".format(movie[cat]))
  elif age<18:
    cat = "Teen"
    print("You fall under Teen Categroy ")
    print("Here are some suggestions for you {}".format(movie[cat]))
  elif age<50:
    cat = "Adult"
    print("You fall under Adult Categroy ")
    print("Here are some suggestions for you {}".format(movie[cat]))
  else:
    cat = "Senior"
    print("You fall under Senior Categroy ")
    print("Here are some suggestions for you {}".format(movie[cat]))
cre()

# Question 5

import random
# Subid is going to be the list of our subscriber ids
subid = []

for i in range(50):
  subid.append(random.randint(0,1000))

evensubid = []
for i in subid:
  if i%2==0:
    evensubid.append(i)
print(evensubid)
# Even subid is the required output

# Question 6
def cnss():
  print("Welcome to the Corporate Network security system")
  spw = "A1234"
  while True:
    pw = input("Please enter the password to continue ")
    if pw==spw:
      print("Verified! Now you can access all your documents")
      break;
    else:
      print("Wrong Password detected")
cnss()

"""## Lab 3"""

# Question 7
scores = [8,9,2,5,7,9,2,1,1,1,10]
import statistics
def scr(l):
  mean = statistics.mean(l)
  med = statistics.median(l)
  stdev = statistics.stdev(l)
  print("Mean, Median and Standad Deviation of the data are {}, {}, {}".format(mean,med,stdev))

scr(scores)

# Question 8

class sma:
  def __init__(self, comm):
    self.comm = []
  def addcom(self,s):
    self.comm.append(s)
  def getdets(self):
    ucom = []
    c = self.comm
    for i in c:
      i.strip()
      cn = 0
      for j in i:
        if j in ["a","e","i","o","u"]:
          cn+=1
      if cn > 10:
        ucom.append([i,cn])
    return ucom
  def __main__():
    sma1 = sma()
    sma1.addcom("hello world")
    sma1.addcom("hello buddy, how are you")
    sma1.addcom("yellow, blue, orange, red, whatever add")
    dets = sma1.getdets()
    print(dets)

# Question 9

"""### Lav 4"""

# Question 10
la = 1000
def loan():
  if la!=0:
    print("Your current loan is {}".format(la))
    x = int(input("Enter the amount you want to pay "))
    la = la - x
  else:
    print("Your loan is already paid")
def si():
  p = float(input("Enter the priciple amount "))
  t = float(input("Enter the time period "))
  r = float(input("enter the rate of interest"))
  s = p*t*r*0.01
  print("Your interest is {}".format(s))

def rfc():
  x = int(input("Please enter 1 for loan payment 2 for calculatin interest"))
  try:
    if x<3:
      if x ==1:
        loan()
      else:
        si()
    else:
      rfc()
  except:
    print("Enter the value again")
    rfc()
rfc()

# Question 11
votea = 0
voteb = 0
def vote():
  try:
    x = input("Enter the party ")
    if x=="a":
      vtoea+=1
    elif x=="b":
      voteb+=2
    else:
      print("Please enter the value again")
      vote()

  except:
    print("please enter the correct value")

# Question 12
def div():
  a = int(input("Enter the first value "))
  b = int(input("Enter the second value "))
  try:
    res = a/b
    print(res)
  except ZeroDivisionError:
    print("Enter the correct Value")
def mult():
  a = int(input("Enter the first value "))
  b = int(input("Enter the second value "))
  print(a*b)
def cal():
  x = int(input("Please enter 1 for division and 2 for multiplication "))
  if x == 1:
    div()
  elif x == 2:
    mult()
cal()

# Question 13
count = 0
def log():
  count=0
  f = open("/content/sample_data/logdata0.txt",'w')
  f.write("Up time {}".format(count))
  count=count+1
  f.close()
log()

# Question 14
def rdlog():
  f = open("/content/sample_data/logdata0.txt",'r')
  print(f.read())

rdlog()

# Question 15